apiVersion: v1
kind: Namespace
metadata:
  name: governance
---
apiVersion: v1
kind: Service
metadata:
  name: governance-arc
  namespace: governance
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: governance-arc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-arc
  namespace: governance
spec:
  replicas: 5
  selector:
    matchLabels:
      app: governance-arc
  template:
    metadata:
      labels:
        app: governance-arc
    spec:
      containers:
      - name: hello-arc
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
